EssenciaWebsite/EssenciaWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('FirstLevel.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EssenciaWebsite/FirstLevel/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('login1/', views.after_register, name='after_register'),
    path('clients/', views.clients, name='clients'),
    path('vision/', views.vision, name='vision'),
    path('principle/', views.principle, name='principle'),
    path('whatwedo/', views.whatwedo, name='whatwedo'),
    path('strength/', views.strength, name='strength'),
    path('L_T_MIS/', views.L_T_MIS, name='L_T_MIS'),
    path('Billing/', views.L_T_BILLING, name='L_T_BILLING'),
    path('IDFC_TW_MIS/', views.IDFC_TW_MIS, name='IDFC_TW_MIS'),
    path('Employee_database/', views.employee_database, name='employee_database'),
]

EssenciaWebsite/FirstLevel/models.py
from django.db import models
# Create your models here.


class UserProfileInfo(models.Model):
    # create relationship(don't inherit from User!)

    # Add any additional attributes you want
    # These name should be similar to the names in forms.py
    username = models.CharField(max_length=30, blank=False, unique=True)
    email = models.EmailField(max_length=60, blank=False, unique=True)
    confirm_email = models.EmailField(blank=False, unique=True)
    password = models.CharField(max_length=30, blank=False)
    confirm_password = models.CharField(max_length=30, blank=False)
    birth_date = models.DateField(blank=False)
    First_Name = models.CharField(max_length=30, blank=False)
    Last_Name = models.CharField(max_length=30, blank=False)
    Emp_ID = models.CharField(max_length=6, blank=False, unique=True)

    def __str__(self):
        return self.username+','+self.password+','+self.Emp_ID

    @classmethod
    def get(cls, param):
        pass

class loginpage(models.Model):
    password = models.CharField(max_length=30, blank=False)
    username = models.CharField(max_length=30, blank=False)
    Emp_ID = models.CharField(max_length=6, blank=True)


class Employee(models.Model):
    NAMES = models.CharField(max_length=50, unique=True, null=False)
    EMPLOYEE_ID = models.CharField(max_length=4, unique=True, null=False)
    MANAGER_ID = models.CharField(max_length=4, null=True)
    MANAGEMENT_LEVEL = models.CharField(max_length=20, null=False)
    DESIGNATION = models.CharField(max_length=20, null=False)
    STAFF = models.CharField(max_length=7 ,null=False)
    EMPLOYEE_STATUS = models.CharField(max_length=20, null=False)
    PROCESS = models.CharField(max_length=20, null=False)
    DEPARTMENT = models.CharField(max_length=15, null=False)
    TYPE_OF_SALARY = models.CharField(max_length=30, null=False)
    SALARY = models.IntegerField(null=False)
    DATE_OF_BIRTH = models.DateField(null=False)
    LOCATION_ID = models.CharField(max_length=10, null=True)
    PHONE_NUMBER = models.IntegerField(null=False)
    HIRE_DATE = models.DateField(null=False)
    END_DATE = models.DateField(null=True)
    DEPARTMENT_ID = models.CharField(max_length=10,null=True)

EssenciaWebsite/FirstLevel/forms.py
from django import forms
from .models import UserProfileInfo, loginpage, Employee
# we always use .models or .forms to import data from models or forms respectively

YEARS = [x for x in range(1940,2021)]

class UserForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    confirm_email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))
    First_Name = forms.CharField()
    Last_Name = forms.CharField()
    Emp_ID = forms.CharField()
    class Meta():
        model = UserProfileInfo
        fields = '__all__'

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['confirm_email']
        password = all_clean_data['password']
        vpassword = all_clean_data['confirm_password']
        emp_id = all_clean_data['Emp_ID']
        date_of_birth = all_clean_data['birth_date']

        if (vpassword != password) or (email != vemail):
            raise forms.ValidationError('')
        elif (vpassword == password) or (email == vemail):
            EE = Employee.objects.order_by('NAMES')
            for E in EE:
                employeeid = E.EMPLOYEE_ID
                dateofbirth = E.DATE_OF_BIRTH
                print(employeeid)
                print(dateofbirth)
                if (emp_id != employeeid) or (date_of_birth != dateofbirth):
                    continue
                else:
                    return
            raise forms.ValidationError('')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    Emp_ID = forms.CharField()

    class Meta():
        model3 = loginpage
        fields3 = ('password', 'username', 'Emp_ID')

    def clean(self):
        all_clean_data = super().clean()
        Emp_ID = all_clean_data['Emp_ID']
        username = all_clean_data['username']
        password = all_clean_data['password']
        print(Emp_ID, username, password)

        # Taking out data from the pre saved database of UserProfileInfo
        username1 = UserProfileInfo.objects.order_by('username')
        for u in username1:
            username11 = u.username
            password1 = u.password
            Emp_ID1 = u.Emp_ID
            print(username11)
            print(password1)
            print(Emp_ID1)
            if (password != password1) or (username != username11) or (Emp_ID != Emp_ID1):
                continue
            else:
                return True
        raise forms.ValidationError('')

EssenciaWebsite/FirstLevel/views.py
from django.shortcuts import render
from .forms import UserForm, LoginForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.core.files.storage import FileSystemStorage
import pandas as pd
import numpy as np
import os

from .models import Employee
from .resources import EmployeeResources
from django.contrib import messages
from tablib import Dataset

# Create your views here.

# front Page
def index(request):
    return render(request, 'FirstLevel/index.html')

# Client Page
def clients(request):
    return render(request, 'FirstLevel/clients.html')

def vision(request):
    return render(request, 'FirstLevel/vision_mission.html')

def principle(request):
    return render(request, 'FirstLevel/principle.html')

def strength(request):
    return render(request, 'FirstLevel/strength.html')

def whatwedo(request):
    return render(request, 'FirstLevel/whatwedo.html')

# After Login- Logout redirect page
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

# for user register
def register(request):
    if request.method == 'POST':
        # taking all data from UserForm in user_form
        user_form = UserForm(data=request.POST)
        # checking the validity of user_form
        if user_form.is_valid():
            # saving the user form
            user = user_form.save()
            user.save()
            return HttpResponseRedirect(reverse('basic_app:after_register'))
        # if there will be an error
        else:
            user_form = UserForm()
            return render(request, 'FirstLevel/register.html', {'user_form': user_form, 'Error': 'MAKE SURE PASSWORD or EMAIL MATCHES!!!'})
            print(user_form.errors)
    # for first initialisation of registration page
    else:
        user_form = UserForm()
    return render(request, 'FirstLevel/register.html', {'user_form': user_form})

# login form / login page
def user_login(request):
    # checking of login form
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        # taking to username for the database
        username = request.POST.get('username')
        empp = request.POST.get('Emp_ID')

        EE = Employee.objects.order_by('NAMES')
        for E in EE:
            employeeid = E.EMPLOYEE_ID
            print(employeeid)
            if (empp != employeeid):
                continue
            else:
                D = E.DESIGNATION

        # Again Checking the form validity
        if login_form.is_valid():
            return render(request, 'FirstLevel/home.html', {'name': username, 'Designation':D})
        else:
            login_form = LoginForm()
            return render(request, 'FirstLevel/login.html', {'login_form': login_form,
                                                             'Error': 'MAKE SURE PASSWORD or EMAIL MATCHES!!!'})
            print('someone tried to login and failed!!!')
    else:
        login_form = LoginForm()
    return render(request, 'FirstLevel/login.html', {'login_form': login_form})

def after_register(request):
    # checking of login form
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        # taking to username for the database
        username = request.POST.get('username')
        # Again Checking the form validity
        if login_form.is_valid():
            return render(request, 'FirstLevel/home.html', {'name': username})
        else:
            login_form = LoginForm()
            return render(request, 'FirstLevel/login.html', {'login_form': login_form,
                                                             'Error': 'MAKE SURE PASSWORD or EMAIL MATCHES!!!'})
            print('someone tried to login and failed!!!')
    else:
        re= 'THANKS FOR REGISTER'
        login_form = LoginForm()
    return render(request, 'FirstLevel/login.html', {'login_form': login_form,'re':re})


def employee_database(request):
    if request.method == 'POST':
        person_resource = EmployeeResources()
        dataset=Dataset()
        new_person=request.FILES['employee']

        if not new_person.name.endswith('xlsx'):
            messages.info(request,'wrong formate')
            return render(request,'FirstLevel/employee_database.html')
        imported_data = dataset.load(new_person.read(),format='xlsx')
        for data in imported_data:
            value = Employee(
                data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10],
                data[11], data[12], data[13], data[14], data[15], data[16])
            value.save()
    return render(request,'FirstLevel/employee_database.html')




# to upload a file
def L_T_MIS(request):
    excel_data = []
    F1 = pd.DataFrame()
    if request.method == 'POST':
        Allocation1 = request.FILES['Allocation']
        Paidfile1 = request.FILES['Paid_File']
        A = pd.read_excel(Allocation1)
        B = pd.read_excel(Paidfile1)
        # for check of file
        for i in range(0, len(A['AGREEMENTID'])):
            if pd.isnull(A['AGREEMENTID'][i]) == True:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'AGREEMENTID DOES NOT TAKE NULL VALUES'})
            elif pd.isnull(A['CUSTOMERNAME'][i]) == True or isinstance(A.loc[i,'CUSTOMERNAME'],str)==False:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'CUSTOMERNAME DOES NOT TAKE NULL VALUES'})
            elif pd.isnull(A['TC NAME'][i]) == True or isinstance(A.loc[i,'TC NAME'],str)==False:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'TC NAME DOES NOT TAKE NULL VALUES'})
            elif pd.isnull(A['TL'][i]) == True or isinstance(A.loc[i,'TL'],str)==False:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'TL DOES NOT TAKE NULL VALUES'})
            elif pd.isnull(A['FOS'][i]) == True or isinstance(A.loc[i,'FOS'],str)==False:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'FOS DOES NOT TAKE NULL VALUES'})
            elif pd.isnull(A['AREA'][i]) == True or isinstance(A.loc[i,'AREA'],str)==False:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'AREA DOES NOT TAKE NULL VALUES'})
            elif isinstance(A.loc[i,'BKT'],np.int64)==False or pd.isnull(A['BKT'][i]) == True:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'BKT DOES NOT TAKE STR VALUES'})
            elif isinstance(A.loc[i,'POS'],np.float64)==False or pd.isnull(A['POS'][i]) == True:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'POS DOES NOT TAKE STR VALUES'})
            elif isinstance(A.loc[i,'EMI'],np.int64)==False or pd.isnull(A['EMI'][i]) == True:
                print('error',i)
                return render(request, 'FirstLevel/upload_excel.html', {'error': 'EMI DOES NOT TAKE STR VALUES'})
            else:
                continue

        fs = FileSystemStorage(location='media/L_T/MIS')
        fs.save(Allocation1.name, Allocation1)
        fs.save(Paidfile1.name, Paidfile1)
        print(A.head())

        B1 = pd.DataFrame(B.groupby('AGREEMENTID')['PAID AMOUNT'].sum()).reset_index()

        for i in range(0, len(A['AGREEMENTID'])):
            for k in range(0, len(B['AGREEMENTID'])):
                if (A.loc[i, 'AGREEMENTID'] == B.loc[k, 'AGREEMENTID']) and (B.loc[k, 'AGAINST'] != 'FORECLOSE' and B.loc[k, 'AGAINST'] != 'SETTLEMENT'):
                    for j in range(0, len(B1['AGREEMENTID'])):
                        if A.loc[i, 'AGREEMENTID'] == B1.loc[j, 'AGREEMENTID']:
                            if (A.loc[i, 'BKT'] != 0 and A.loc[i, 'BKT'] != 12) and (A.loc[i, 'BKT'] != 1):
                                a = (int(A.loc[i, 'BKT']) + 1) * A.loc[i, 'EMI']
                                b = A.loc[i, 'EMI'] + A.loc[i, 'EMI']
                                if (B1.loc[j, 'PAID AMOUNT'] >= a) or (B1.loc[j, 'PAID AMOUNT'] >= A.loc[i, 'POS']):
                                    A.loc[i, 'STATUS'] = 'NM'
                                elif (B1.loc[j, 'PAID AMOUNT'] >= b) and (B1.loc[j, 'PAID AMOUNT'] < a) and (B1.loc[j, 'PAID AMOUNT'] < A.loc[i, 'POS']):
                                    A.loc[i, 'STATUS'] = 'RB'
                                elif (B1.loc[j, 'PAID AMOUNT'] >= A.loc[i, 'EMI']) and (B1.loc[j, 'PAID AMOUNT'] < b):
                                    A.loc[i, 'STATUS'] = 'SB'
                                elif B1.loc[j, 'PAID AMOUNT'] < A.loc[i, 'EMI']:
                                    A.loc[i, 'STATUS'] = 'PART PAID'
                            elif A.loc[i, 'BKT'] == 1:
                                b = A.loc[i, 'EMI'] + A.loc[i, 'EMI']
                                if (B1.loc[j, 'PAID AMOUNT'] >= b) or (B1.loc[j, 'PAID AMOUNT'] >= A.loc[i, 'POS']):
                                    A.loc[i, 'STATUS'] = 'NM'
                                elif (B1.loc[j, 'PAID AMOUNT'] >= A.loc[i, 'EMI']) and (B1.loc[j, 'PAID AMOUNT'] < b):
                                    A.loc[i, 'STATUS'] = 'SB'
                                elif B1.loc[j, 'PAID AMOUNT'] < A.loc[i, 'EMI']:
                                    A.loc[i, 'STATUS'] = 'PART PAID'
                            elif A.loc[i, 'BKT'] == 12:
                                c = (int(A.loc[i, 'BKT']) + 1) * A.loc[i, 'EMI']
                                d = A.loc[i, 'EMI'] + A.loc[i, 'EMI']
                                if (B1.loc[j, 'PAID AMOUNT'] >= c) or (B1.loc[j, 'PAID AMOUNT'] >= A.loc[i, 'POS']):

EssenciaWebsite/templates/FirstLevel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial- scale 1.0">
    <title>ESSENCCIA OUTSOURCING</title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/base.css' %}">
</head>
<body>
    <NAV>
        <UL class="img">
            <A href="{% url 'basic_app:index' %}"><IMG SRC="{% static 'FirstLevel/images/logo.png' %}" WIDTH= "100"></A>
        </UL>
        <UL class="nav" style="padding-left:520px; margin-bottom:10px;">
            <LI>
                <A HREF="{% url 'basic_app:index' %}"><strong>HOME</strong></A>
            </LI>
            <LI>
                <A HREF="{% url 'basic_app:vision' %}"><strong>VISION / MISSION</strong></A>
            </LI>
            <LI><A HREF= "#"><strong>ABOUT US</strong></A>
                <UL class="drop">
                    <LI>
                        <A HREF= "{% url 'basic_app:strength' %}"><strong>OUR STRENGTH</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "{% url 'basic_app:principle' %}"><strong>OUR PRINCIPLES</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "{% url 'basic_app:clients' %}"><strong>OUR CLIENTS</strong></A>
                    </LI>
                </UL>
            </LI>
            <LI>
                <a href="{% url 'basic_app:whatwedo' %}"><strong>WHAT WE DO !</strong></a>
            </LI>
            <LI>
                <A HREF= "#"><strong>CONTACT US</strong></a>
                <UL class="drop">
                    <LI>
                        <A HREF= "#"><strong>DIRECTORS</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "#"><strong>WANT TO JOIN</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "{% url 'basic_app:employee_database' %}"><strong>PARTNER WITH US</strong></A>
                    </LI>
                </UL>
            </li>
            <UL class="log">
                <A HREF="{% url 'basic_app:user_login' %}"><strong>LOGIN</strong></A>
            </UL>
        </UL>
    </NAV>
      {% block body_block %}

      {% endblock %}
</body>
</html>

EssenciaWebsite/templates/FirstLevel/clients.html
{% extends 'FirstLevel/base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width , initial- scale 1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/clients.css' %}">
    <style>
        @font-face {
            font-family: Accidental Presidency ;
            src: url("{% static 'FirstLevel/fonts/accid_.ttf' %}");
            }

        @font-face {
            font-family: Arial Narrow;
            src: url("{% static 'FirstLevel/fonts/ARIALNB_2.ttf' %}");
            }

        body{
            background-color: black;
            background-image: url("{% static 'FirstLevel/images/4ps.png' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: 50% 50% ;
            background-size: 500px 450px;
            }

        h1{
            font-size: 36px;
            font-weight: 600;
            font-family: Accidental Presidency;
            color: white;
            text-align: left;
            }
    </style>
</head>
<body>
<SECTION class="course">
    <H1 style="margin-bottom:0px; margin-top:0px">OUR CLIENTS</H1>
    <HR color= #d3ae6d>
    <OL class="breadcrumb" style="margin-top:0px;margin-bottom:0px;padding-left:0px;padding-top:0px;">
        <LI>
            <A href="{% url 'basic_app:index' %}">Home</A>
        </LI>
        <LI>
            <A href="{% url 'basic_app:clients' %}">Our Clients</A>
        </LI>
    </OL>

    <DIV class="row">
        <DIV class="course-col">
            <H3>IDFC CAPITAL FIRST</H3>
            <HR color=#d3ae6d width=30%>
            <IMG class="idfc" src="{% static 'FirstLevel/images/idfc logo.png' %}" alt="">
                <P>IDFC Bank is a universal bank , offering financial solutions through its nationwide branches ,
                    internet and mobile. IDFC Bank offers basic services like savings account , NRI Accounts ,
                    Fixed Deposits , Home Loan , Personal loan among others , using technology and a
                    service - oriented approach , to make banking simple and accessible , anytime and from anywhere.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>BAJAJ FINSERV</H3>
            <HR color=#d3ae6d width=30%>
            <IMG class="idfc" src="{% static 'FirstLevel/images/bajaj.jpg' %}" alt="">
                <P> Bajaj Finserv, is an Indian non-banking financial company (NBFC). The company deals in consumer
                    finance, SME (small and medium-sized enterprises) and commercial lending, and wealth management.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>L&T Financial Services </H3>
            <HR color=#d3ae6d width=30%>
            <IMG class="idfc" src="{% static 'FirstLevel/images/l&t logo.png' %}" alt="">
                <P> L&T Finance Holdings Ltd. is a NSE and BSE listed company and is also registered with RBI as an
                    NBFC and CIC. It conducts its financial services businesses through various subsidiaries.
                    L&T Financial Services is the brand name of L&T Finance Holdings Ltd.
                </P>
        </DIV>
    </DIV>

    <DIV class="row2">
        <DIV class="course-col">
            <H3>KOTAK MAHINDRA</H3>
            <HR color=#d3ae6d width=30%>
            <IMG class="idfc" src="{% static 'FirstLevel/images/kotak.png' %}" alt="">
                <P>Kotak Mahindra Bank Limited is an Indian private sector bank headquartered in Mumbai,
                    Maharashtra, India. It offers banking products and financial services for corporate and
                    retail customers in the areas of personal finance, investment banking, life insurance,
                    and wealth management.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>FULLERTON INDIA</H3>
            <HR color=#d3ae6d width=30%>
            <IMG class="idfc" src="{% static 'FirstLevel/images/flurtron.png' %}" alt="">
                <P>Fullerton India Credit Co. Ltd. is a non - banking financial company in India.
                    It is headquartered at Mumbai, India and deals with financing across retail and rural segments.
                    The company provides unsecured as well as secured lending products through a diverse branch network
                    as well as via digital channels to individuals and MSMEs
                </P>
        </DIV>
    </DIV>
</SECTION>
</body>
</html>
{% endblock %}

EssenciaWebsite/templates/FirstLevel/home_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width , initial- scale 1.0">
    <title>ESSENCCIA OUTSOURCING</title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/home_base.css' %}">
    <style>
        UL LI{
            FLOAT:left;
            WIDTH:160PX;
            HEIGHT:33PX;
            BACKGROUND:NONE;
            OPACITY:.8;
            LINE-HEIGHT:31PX;
            MARGIN-RIGHT: 3PX
            }

        UL LI A{
            TEXT-DECORATION: NONE;
            COLOR:WHITE;
            DISPLAY: BLOCK;
            TEXT-ALIGN: CENTER;
            FONT-SIZE: 15PX;
            }
    </style>
</head>
<body>
{% if Designation == 'ADMIN' and PROCESS == 'IDFC' %}
    <NAV style="margin-top:0px;width:1400px;height:100px;margin-bottom:0px;">
        <UL class="img1">
            <A href="#"><IMG SRC= "{% static 'FirstLevel/images/logo.png' %}" WIDTH= "100"></A>
        </UL>
        <UL class="nav" style="float:right; margin-left:0px;margin-top:22px">
            <LI>
                <A HREF="#"><STRONG>SALARIES</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:L_T_BILLING' %}"><STRONG>PROFIT & LOSS</STRONG></A>
            </LI>
            <LI>
                <A href=#><STRONG>ANALYSIS</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:IDFC_TW_MIS' %}"><STRONG>FILE MANAGEMENT</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:employee_database' %}"><STRONG>EMPLOYEES</STRONG></A>
            </LI>
            <ul class="block">
                <A href="{% url 'basic_app:index' %}"><STRONG>LOGOUT</STRONG></A>
            </ul>
        </UL>
    </NAV>
{% else %}
    <NAV style="margin-top:0px;width:1400px;height:100px;margin-bottom:0px;">
        <UL class="img1">
            <A href="#"><IMG SRC= "{% static 'FirstLevel/images/logo.png' %}" WIDTH= "100"></A>
        </UL>
        <UL class="nav" style="float:right; margin-left:0px;margin-top:22px">
            <LI>
                <A HREF="#"><STRONG>DASHBOARD</STRONG></A>
            </LI>
            <LI>
                <A HREF="#"><STRONG>SALARIES</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:L_T_BILLING' %}"><STRONG>PROFIT & LOSS</STRONG></A>
            </LI>
            <LI>
                <A href=#><STRONG>ANALYSIS</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:L_T_MIS' %}"><STRONG>FILE MANAGEMENT</STRONG></A>
            </LI>
            <LI>
                <A HREF= "{% url 'basic_app:employee_database' %}"><STRONG>EMPLOYEES</STRONG></A>
            </LI>
            <ul class="block">
                <A href="{% url 'basic_app:index' %}"><STRONG>LOGOUT</STRONG></A>
            </ul>
        </UL>
    </NAV>
{% endif %}
{% block body_block %}

{% endblock %}
</body>
</html>

EssenciaWebsite/templates/FirstLevel/login.html
{% extends 'FirstLevel/login_base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/login.css' %}">
    <style>
        @font-face {
            font-family: Accidental Presidency ;
            src: url("{% static 'FirstLevel/fonts/accid_.ttf' %}");
            }

        @font-face {
            font-family: Arial Narrow;
            src: url("{% static 'FirstLevel/fonts/ARIALNB_2.ttf' %}");
            }
    </style>
</head>
<body>
    <DIV style="margin-left:570px; margin-right:530px; width:300px;">
        <H1 class='go' style="margin-top:0px">COMPANY LOGIN</H1>
        <FORM class="box" action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}

            {{login_form.as_p}}
            <TABLE style="margin-right: 0px; margin-left: 28px;">
                <TH>
                    <STRONG><INPUT type="submit" name="" value="LOGIN"></STRONG>
                </TH>
                <TH></TH>
                <TH>
                    <A href="{% url 'basic_app:register' %}">New User?</A>
                </TH>
            </TABLE>
        </FORM>
    </DIV>
    <DIV class="error">
        {{Error}}
        {{re}}
    </DIV>
</body>
</html>
{% endblock %}